### ISSUE TITLE
No webgl support found on this computer! Disabled 3d viewer - Sorry!

### ISSUE THREAD

**Issue by devsys** [OpenBuilds/SW-Machine-Drivers#34]
Hello, Have a fresh Windows 10 install, Installed some apps with ninte and openbuilds control. When I load the GUI, I see the error message 

"No WebGL Support found on this computer! Disabled 3d viewer - Sorry!"

What needs to be installed to resolve this depencency? If I go to get.webgl.org it says my browser supports webGL (Firefox)...

**Comment by openbuilds-engineer** [comment]
Not a bug sorry. Either your PC reports it does support the specific WebGL extensions we need, or it doesnt.  If it doesnt, we cant enable the 3D viewer.  

Make sure you have decent graphics drivers, if its onboard, consider a decent GPU.

The WebGL.org test is irrelevant, we are running in our own Electron instance with specific GPU switches, not inside your browser (from where the webgl test runs) - two very different use cases. 

This is how we check: (from inside Electron)
```
var webgl = (function() {
  try {
    return !!window.WebGLRenderingContext && !!document.createElement('canvas').getContext('experimental-webgl');
  } catch (e) {
    return false;
  }
})();
```
