### ISSUE TITLE
Probe wizard for X / Y axis?

### ISSUE THREAD

**Issue by lhilton** [OpenBuilds/SW-Machine-Drivers#57]
Is there any effort underway or planned to implement an X / Y probe wizard? I use a probing system that lets me find the edges as well as surface and having that edge finding portion in the wizard would speed up my work piece setup time.

If there is no complaint about adding this, I can do the dev work and provide a pull request.

**Comment by sharmstr** [comment]
Workaround is to add a macro.  Works great.

**Comment by openbuilds-engineer** [comment]
At this time we only supply a Z Touch-off plate https://openbuildspartstore.com/z-touch-plate/ so the software, officially, only has a Z touch off wizard to match the ecosystem 
As mentioned above, for custom tasks, we have the Macros
