### ISSUE TITLE
Change the color of the gear icon on the macro buttons on hover

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/SW-Machine-Drivers#60]
Will give some visual clue as to where you need to click when you want to edit the macro.

**Comment by openbuilds-engineer** [comment]
Thanks for the reminder (: will do soon

**Comment by openbuilds-engineer** [comment]
Will be in 1.0.151 or later (:

**Comment by openbuilds-engineer** [comment]
https://github.com/OpenBuilds/SW-Machine-Drivers/commit/a4dd9e77623953cc7d8916005b8939a69f2aa5f2 Fixed
