### ISSUE TITLE
Feature Request - help text for macros

### ISSUE THREAD

**Issue by jbhurst** [OpenBuilds/SW-Machine-Drivers#61]
Would love a field in macro setup to enter descriptive text that will pop up when a user hovers over a macro allowing them to see more about what it does.  I'm setting up a machine for operator use and want them to pick from a few predefined actions, but it is hard to describe with an icon and two or three words.

**Comment by openbuilds-engineer** [comment]
Cool idea, will add todo

**Comment by openbuilds-engineer** [comment]
V1.0.151 (out in couple days) will have this:

![tooltip2](https://user-images.githubusercontent.com/31449271/56048353-a099b580-5d47-11e9-848b-91e6f456a57c.PNG)
![tooltips1](https://user-images.githubusercontent.com/31449271/56048355-a099b580-5d47-11e9-969a-4d77f43dbffc.png)

**Comment by jbhurst** [comment]
Thanks!
