### ISSUE TITLE
Homing dropdown in grbl settings is incorrect

### ISSUE THREAD

**Issue by SugarJ68** [OpenBuilds/SW-Machine-Drivers#66]
Look at the dropdown, note that 3 and 4 should be reversed according to the grbl homing wiki linked above......
Homing Direction Dropdown.jpg
3 should be X and Y reversed homing with Z normal, 4 should be X and Y normal with Z reversed. I set it to 3 and my machine homes properly like it used to with the TinyG board.
![Homing Direction Dropdown](https://user-images.githubusercontent.com/49738521/56331839-cc031280-6142-11e9-80a8-821447ba896f.jpg)

**Comment by openbuilds-engineer** [comment]
Will check shortly! Thanks!

**Comment by openbuilds-engineer** [comment]
v1.0.157 or later will have this fixed!
