### ISSUE TITLE
Display job duration/remaining time

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/SW-Machine-Drivers#67]
https://openbuilds.com/threads/openbuilds-control-software.13121/page-14#post-80639

**Comment by openbuilds-engineer** [comment]
Now I got to go and remember the history.  It worked at some point, then didnt... from the old LW days some of this code came. 

We do calc the time for each segment still...  Will check later

https://github.com/OpenBuilds/SW-Machine-Drivers/blob/master/app/lib/3dview/workers/gcodeparser.js#L817-L836

**Comment by openbuilds-engineer** [comment]
![timesum](https://user-images.githubusercontent.com/31449271/56360178-15576e80-61e4-11e9-81a5-b18e522128d0.PNG)

Well, good news is I have the sum of all the moves stores on the userData for each line segment.  So we can do something simple:

total time = object.userData.lines[object.userData.lines.length-1].p2.timeMinsSum
remaining time = total time - (runtime so far or from  object.userData.lines[numberoflinesalreadysent].p2.timeMinsSum)

**Comment by openbuilds-engineer** [comment]
Concept checks out:

![data](https://user-images.githubusercontent.com/31449271/56360537-3d939d00-61e5-11e9-9cda-a511e577f4c5.PNG)
Will add it as overlay on the bottom progress bar in next release (and formatted nicer)

**Comment by sharmstr** [comment]
Awesome!

**Comment by openbuilds-engineer** [comment]
![progress and time](https://user-images.githubusercontent.com/31449271/56367614-e8ac5280-61f5-11e9-903a-784d5c064db9.PNG)

v1.0.156 or later (:
