### ISSUE TITLE
404 error on machine image when no machine config set

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/SW-Machine-Drivers#68]
Low priority.

When no machine config is selected Control looks for " http://localhost:3000/img/mch/.png ".  Perhaps just load the custom machine image?

![404](https://user-images.githubusercontent.com/5436091/56360977-0a2c2080-619b-11e9-9481-d33ad1ea3b6c.png)

**Comment by openbuilds-engineer** [comment]
v1.0.157 or later fixed (:
