### ISSUE TITLE
key leaked in repository

### ISSUE THREAD

**Issue by hildred** [OpenBuilds/SW-Machine-Drivers#70]
including private keys in public repositories is a bad idea. account-key.txt is now compromised. see https://snyk.io/blog/ten-git-hub-security-best-practices/ or https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda?gi=d45aaa91d584

**Comment by openbuilds-engineer** [comment]
Thanks, will attend, that key is restricted to read only for the git API only so we can pull release info for the Update, so not a crisis.

**Comment by openbuilds-engineer** [comment]
Reissued and removed from Repo
