### ISSUE TITLE
Add more functionality to jog widget

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/SW-Machine-Drivers#71]
Feature request:  https://openbuilds.com/threads/openbuilds-control-software.13121/page-14#post-80759

"It would be awesome to control the probes, start, stop, home all etc... all from the widget if possible. "

**Comment by openbuilds-engineer** [comment]
Sure (: its overdue (maybe not all of it though but the DRO+cursors can be copied from the main app)

**Comment by openbuilds-engineer** [comment]
Fixed the buggy behavior and added the DRO Block from the main application to v1.0.157 or later. 

Will sleep on the home/control/etc options for a couple - not too urgent 
![new dro](https://user-images.githubusercontent.com/31449271/56501204-2d91fb00-650e-11e9-9ec2-962507eaac1f.PNG)
