### ISSUE TITLE
Multiple Custom Machines Profiles

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/SW-Machine-Drivers#74]
https://openbuilds.com/threads/openbuilds-control-software.13121/page-16#post-81372

" I was wondering if there's plans to include the option to create and name your own machine? 
I like the idea of the drop down, but what if what you have doesn't quite fit? There's no way of saving more than one custom machine, nor is there the ability to change the preconfigured names already in the list. I have a workbee 750 that I'd like to name in there, and have my laser frame included in the mix. Plus, I will be adding a rotary axis, so having a 3rd option to add a machine profile for that would be nice so I didn't have to reconfigure my axes every time..
That would be a nice touch."

**Comment by openbuilds-engineer** [comment]
The profiles just prepopulate the Grbl settings form for users.  Custom profiles would not really make sense. "custom" as is just sets the stuff people usually forgot like $4=1
